### ISSUE TITLE
fake

### ISSUE THREAD

**Issue by buptmuye** [John-Lin/nat#1]
看到github上你写的nat，十分赞。能否问下self.fake_mac_eth1和self.fake_mac_eth2应当如何设置呢？我之前尝试过self.fake_mac_eth1设为lan口的mac，self.fake_mac_eth2设置为ovs的网桥dpid，但是不成功，log显示sending arp request。

**Comment by John-Lin** [comment]
兩個 fake_mac 皆是假的 實際不需要設置
