### ISSUE TITLE
dhcp.py has type error 

### ISSUE THREAD

**Issue by MuntherN** [John-Lin/nat#2]
greeting ,

at first, thank you for great work.

when I run dhcp.py with Ryu controller on Linux VM I used the command below: 

 ./bin/ryu-manager --verbose ryu/app/nat-master/dhcp.py

and I get the error below: 
loading app ryu/app/nat-master/dhcp.py
loading app ryu.controller.ofp_handler
instantiating app ryu/app/nat-master/dhcp.py of SimpleDHCPServer
Failed when loading pickled
Traceback (most recent call last):
  File "./bin/ryu-manager", line 19, in <module>
    main()
  File "/home/ubuntu/ryu/ryu/cmd/manager.py", line 91, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/home/ubuntu/ryu/ryu/base/app_manager.py", line 484, in instantiate_apps
    self._instantiate(app_name, cls, *args, **kwargs)
  File "/home/ubuntu/ryu/ryu/base/app_manager.py", line 470, in _instantiate
    app = cls(*args, **kwargs)
  File "/home/ubuntu/ryu/ryu/app/nat-master/dhcp.py", line 37, in __init__
    self.dhcp_addr = dhcp_settings['dhcp_gw_addr']
TypeError: 'NoneType' object has no attribute '__getitem__'

if you can help me to run dhcp.py without errors .
best regards

**Comment by John-Lin** [comment]
You should do initialization when you start to use it. Please check README initialize section. 
https://github.com/John-Lin/nat#initialize

**Comment by MuntherN** [comment]
Thank you for replay , so i can not run DHCP.py alone ?

**Comment by John-Lin** [comment]
Yes. But you can modify code to meet your requirements.
